# Hi All


 ## We are learning Python with Jupyter Notebook

Basic Python Introduction Studies

## SECTION : INTRO

In [ ]:
# The first code

3+3 

6

In [ ]:
# Step by step

4/3

1.3333333333333333

In [ ]:
# Value

3.2

3.2

In [ ]:
# Invalid  Variable

"c"

'c'

In [ ]:
# Variable

a=3

a

3

In [ ]:
a = 9

b = 10

In [ ]:
a * b

90

In [ ]:
a + b

19

In [ ]:
print("Python")

Python


In [ ]:
print(a)

9


In [ ]:
print("En sevdigim sayi : ",3)

En sevdigim sayi :  3


In [ ]:
a = input()

7


In [ ]:
a

'7'

In [ ]:
# Read Data

a = input()

print(a)

5
5


In [1]:
### Read Data for Calculation

a = int(input())
b = int(input())


print(a*b)

5
20
100


In [ ]:
### Read Data for Calculation

a = (input())
b = (input())

a=int(a)
b=int(b)

print(a+b)

2
4
6


In [ ]:
# Methods 

type("merhaba")

str

In [3]:
type('2323')

str

In [4]:
a=3

In [5]:
type(a)

int

In [ ]:
a='elma'

In [ ]:
type(a)

str

In [ ]:
type(b)

int

In [ ]:
c=4/3

In [ ]:
type(c)

float

In [ ]:
c= 3.4
type(c)

float

In [ ]:
info = "Assignments Operations"

In [ ]:
type(info)

str

In [ ]:
info.count("s")

4

In [ ]:
info.upper()

'ASSIGNMENTS OPERATIONS'

In [ ]:
info.lower()

'assignments operations'

In [ ]:
info.replace(" ", "????")

'Assignments????Operations'

In [ ]:
info

'Assignments Operations'

In [ ]:
info = info.replace(" ", "=")

In [ ]:
info.upper()

'ASSIGNMENTS=OPERATIONS'

In [ ]:
info.replace("=", ":")

'Assignments:Operations'

In [ ]:
info = info.upper()

In [ ]:
info.replace(" ", "=")

'ASSIGNMENTS=OPERATIONS'

In [ ]:
info.upper().replace(" ", "=")

'ASSIGNMENTS=OPERATIONS'

In [ ]:
"ASD".isupper()

True

In [ ]:
"AsD".isupper()

False

In [ ]:
"YESIL".isupper()+"AÇIK".isupper()

2

In [ ]:
# Assignments Operations

In [ ]:
info = "Assignments Operations"
info

'Assignments Operations'

In [ ]:
info.upper()

'ASSIGNMENTS OPERATIONS'

In [ ]:
info.lower()

'assignments operations'

In [ ]:
info.replace(" ", "=")

'Assignments=Operations'

In [ ]:
"ASs".isupper()

False

In [ ]:
info.isupper()

False

## SECTION : DATA TYPES

In [ ]:
# Data Types & Integer

x = 18
type(x)

int

In [ ]:
# Data Types & Integer

y = 4.2
type(y)

float

In [ ]:
# Data Types & String

a = "Hello World"
type(a)

str

### LIST

In [ ]:
my_list = [3,3,4, 'a',True]

In [ ]:
my_list

[3, 3, 4, 'a', True]

In [ ]:
len(my_list)

5

In [ ]:
#[3, 3, 4, 'a', True]
#[0, 1, 2,  3,   4]

In [ ]:
my_list[2]  #2. indeks... 0,1,2,3...

4

In [ ]:
my_list[3]

'a'

In [ ]:
my_list[-2]

'a'

In [ ]:
my_list[2:4] 

[4, 'a']

In [ ]:
my_list[3]='miuul'

In [ ]:
my_list

[3, 3, 4, 'miuul', True]

### TUPLE

In [8]:
my_tuple =(3,3,4,'a')

In [9]:
my_tuple

(3, 3, 4, 'a')

In [10]:
my_tuple[2]

4

In [ ]:
my_tuple_list = list(my_tuple)

In [ ]:
type(my_tuple_list)

list

### SET

In [ ]:
my_set ={3,3,4,'a'}

In [ ]:
my_set

{3, 4, 'a'}

In [ ]:
y = {5,3}

In [ ]:
my_set.issubset(y)

False

In [ ]:
y.issubset(my_set)

True

In [ ]:
my_set.union(y)

{3, 4, 5, 'a'}

In [ ]:
my_set.intersection(y)

{3}

In [ ]:
my_set.difference(y)

{4, 'a'}

### DICTIONARY

In [ ]:
my_dict = {"Name": "Arda","Age": 40}

In [ ]:
my_dict 

{'Name': 'Arda', 'Age': 40}

In [ ]:
my_dict.keys()

dict_keys(['Name', 'Age'])

In [ ]:
my_dict.values()

dict_values(['Arda', 40])

## SECTION 3 : LIST is THE BEST

* Practice 1

In [ ]:
text = "Once you stop learning, you-start dying."

In [ ]:
text.upper()

'ONCE YOU STOP LEARNING, YOU-START DYING.'

In [ ]:
text.replace(",", " | ")

'Once you stop learning |  you-start dying.'

In [ ]:
text = text.split('-')

In [ ]:
text

['Once you stop learning, you', 'start dying.']

In [ ]:
text.upper().replace(",", "$$$$").replace(".", "%%%").split("-")

['ONCE YOU STOP LEARNING$$$$ YOU', 'START DYING%%%']

In [ ]:
text.upper().replace(",", "$$$$").replace(".", "%%%").split()

['ONCE', 'YOU', 'STOP', 'LEARNING$$$$', 'YOU-START', 'DYING%%%']

* Practice 2

In [ ]:
my_list = ["D","A","T","A"," ","S","C","I","E","N","C","E"]
my_list

['D', 'A', 'T', 'A', ' ', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [ ]:
type(my_list)

list

In [ ]:
my_listst="DATA SCIENCE"

In [ ]:
type(my_listst)

str

In [ ]:
len(my_list)

12

In [ ]:
my_list[11]

'E'

In [ ]:
my_list[len(my_list)-1]

'E'

In [ ]:
my_list[-1]

'E'

In [ ]:
my_list[0]

'D'

In [ ]:
my_list = my_list.lower()

['D', 'A', 'T', 'A', 'XX', ' & ', ' ', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [ ]:
my_list[0:5]

['D', 'A', 'T', 'A', ' ']

In [ ]:
my_list[0:4]+my_list[4:12]

['D', 'A', 'T', 'A', ' ', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [ ]:
my_list # Ekleme

['D', 'A', 'T', 'A', ' ', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [ ]:
my_list.insert(4, "XX")
my_list

['D', 'A', 'T', 'A', 'XX', ' ', 'S', 'C', 'I', 'E', 'N', 'C', 'E']

In [ ]:
len(my_list)

13

In [ ]:
my_list = [1,2,3,[10,20,30],4]

In [ ]:
# my_list_plus = [1,2,3,[10,20,[1,2,3,[10,20,30],4,1,2,3,[10,20,30],4]],4]

In [ ]:
my_list[3][2]

30

In [ ]:
my_list[3]

[10, 20, 30]

In [ ]:
my_list[3][2]

30

In [ ]:
my_list[2:4]

[3, [10, 20, 30]]

In [ ]:
my_list[4:]

[4]

In [ ]:
my_list = ["D","A","T","A"," ","S","C","I","E","N","C","E"]

In [ ]:
"-".join(my_list)

'D-A-T-A- -S-C-I-E-N-C-E'

In [ ]:
date = ["25","09","2022"]
"/".join(date)

'25/09/2022'

In [ ]:
my_list.count("A")

2

In [ ]:
viki = "Albert Einstein (Almanca telaffuz Tüm zamanların en iyi fizikçilerinden kabul edilen Einstein, en çok görelilik teorisini geliştirmesiyle tanınır."

In [ ]:
viki_list = viki.split()

In [ ]:
viki_list

['Albert',
 'Einstein',
 '(Almanca',
 'telaffuz',
 'Tüm',
 'zamanların',
 'en',
 'iyi',
 'fizikçilerinden',
 'kabul',
 'edilen',
 'Einstein,',
 'en',
 'çok',
 'görelilik',
 'teorisini',
 'geliştirmesiyle',
 'tanınır.']

In [ ]:
viki_list[0].count("e")

1

In [ ]:
viki.count("e")

15

## SECTION : FOR

In [ ]:
# ben bir n'im.. listede gezerim. Her turda bir sayiyi tasirim

In [ ]:
for u in [3,4,40]:
    print(u)
    a = u*u
    print(a)
    print("----")

3
9
----
4
16
----
40
1600
----


In [ ]:
for u in [3,4,40,14]:
    u = u+1
    print(u)

4
5
41
15


In [ ]:
for k in ["Age","Gender","Income","City"]:
    print(k)

Age
Gender
Income
City


In [ ]:
a=0

for d in [3,4,40]:
  a = a + d
  print(a)

3
7
47


a 0 d 3 --> a = 3 <br>
a 3 d 4 --> a = 7 <br>
a 7 d 40 --> a = 47

In [ ]:
a=0

for d in [3,4,40]:
  a = a + d

print(a)

47


In [ ]:
x = range(0, 10 ,2)

xy = [0,2,4,6,8]

for n in x:
  print(n)

0
2
4
6
8


In [ ]:
xy = [0,2,4,6,8]

for n in xy:
  print(n)

0
2
4
6
8


In [ ]:
x = range(0, 10,2)
a = 0
for n in x:
  a =n+3
  print(a)

3
5
7
9
11


In [ ]:
x = range(0, 10,2)

for n in x:
  print(n)

0
2
4
6
8


In [ ]:
def derya():
    x = range(0, 10,2)
    for n in x:
        print(n)
        

In [ ]:
derya()

0
2
4
6
8


In [ ]:
def for_ogreniyorum(a,b,c):
    x = range(a, b,c)
    for n in x:
        print(n)

In [ ]:
for_ogreniyorum(1,20,4)

1
5
9
13
17


In [ ]:
for_ogreniyorum(4,54,3)

4
7
10
13
16
19
22
25
28
31
34
37
40
43
46
49
52


In [ ]:
# Bonus soru :)
def for_ogreniyorum(c):
    c=int(c)
    x = range(0, 10,c)
    for n in x:
        print(n)

In [ ]:
for_ogreniyorum(input())

2
0
2
4
6
8


In [ ]:
# Bonus soru :)
def for_ogreniyorum(a,b,c):
    a=int(a)
    b=int(b)
    c=int(c)
    x = range(a,b,c)
    for n in x:
        print(n)

In [ ]:
for_ogreniyorum(input(),input(),input())

0
100
3
0
3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
51
54
57
60
63
66
69
72
75
78
81
84
87
90
93
96
99


## SECTION : FUNCTIONS

In [ ]:
2+3

5

In [ ]:
def sum_function():
    

    print("The first number : ")
    
    num1 = int(input())
    
    print("The second number : ")
    
    num2 = int(input())
    
    print("Total: ",num1 + num2)
    

In [ ]:
sum_function()

The first number : 
2
The second number : 
8
Total:  10


## SECTION : DATA MANUPLATION - NUMPY

In [ ]:
import numpy as np

In [ ]:
a = [10,20,30,40]
b = [22,23,24,25]

In [ ]:
len(a)

4

In [ ]:
b[3]

25

In [ ]:
ab = []

In [ ]:
ab

[]

In [ ]:
ab.append(7)

In [ ]:
ab

[3, 7, 7]

In [ ]:
range(0, len(a))

range(0, 4)

In [ ]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i] + b[i])
        
    
ab

[32, 43, 54, 65]

0 1 2 3

In [ ]:
3+3

6

In [13]:
import numpy as np

In [14]:
np.empty([2, 2])

array([[0.000e+000, 1.714e-321],
       [9.881e-324, 9.881e-324]])

In [ ]:
a = np.array([10,20,30,40])
b = np.array([22,23,24,25])

In [ ]:
a = np.array([10,20,30,40])

In [ ]:
a

array([10, 20, 30, 40])

In [ ]:
b

array([22, 23, 24, 25])

In [ ]:
a = np.array([10,20,30,40,60,70,80,90])

In [ ]:
a<30

array([ True,  True, False, False, False, False, False, False])

In [ ]:
a[3]

40

In [ ]:
a[[ True,  True, False, False, False, False, False, False]]

array([10, 20])

In [ ]:
a[a < 30]

array([10, 20])

In [ ]:
a

array([10, 20])

In [ ]:
& | 

In [ ]:
a = np.array([10,20,30,40,60,70,80,90])

In [ ]:
a[(a > 20) & (a >60) ]

array([70, 80, 90])

In [ ]:
a

array([10, 20, 30, 40, 60, 70, 80, 90])

In [ ]:
x = 50
y = 40


if x>y:
    print(x)
    

50


In [ ]:
x = 40
y = 50


if x>y:
    print(x)
else:
    print(y)

50


In [ ]:
a

array([10, 20, 30, 40, 60, 70, 80, 90])

In [ ]:
ab = []

for i in a:
    if i < 70:
        ab.append(i)

In [ ]:
ab

[10, 20, 30, 40, 60]

In [ ]:
a[a<70]

array([10, 20, 30, 40, 60])

## SECTION : DATA MANUPLATION - PANDAS

In [ ]:
import pandas as pd

In [ ]:
my_list = [10,20,30,40]

In [ ]:
my_list

[10, 20, 30, 40]

In [ ]:
pd.DataFrame(my_list)

0
0  10
1  20
2  30
3  40

In [ ]:
df = pd.DataFrame(my_list, columns = [["Age",'Gender']])

Age
0   10
1   20
2   30
3   40

In [ ]:
np.arange(1,51).reshape((2,25))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [ ]:
m = np.arange(1,10).reshape((3,3))

In [ ]:
m = np.arange(1,10)

In [ ]:
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
m= m.reshape((3,3))

In [ ]:
m = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

In [ ]:
m[1][2]*m[1][1]

30

In [ ]:
pd.DataFrame(m, columns = ["Age1", "Age2","Age3"])

Age1  Age2  Age3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
df = pd.DataFrame(m, columns = ["Age1", "Age2","Age3"])

In [ ]:
df

Age1  Age2  Age3
0     1     2     3
1     4     5     6
2     7     8     9

In [ ]:
df.shape

(3, 3)

In [ ]:
df.ndim

2

In [ ]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df.index = ["Hava","Toprak","Su"]

In [ ]:
df.columns

Index(['Age1', 'Age2', 'Age3'], dtype='object')

In [ ]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
df.index = ["a","b","c"]

In [ ]:
df

Age1  Age2  Age3
a     1     2     3
b     4     5     6
c     7     8     9

In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import seaborn as sns

In [ ]:
import seaborn as sns

In [ ]:
df = sns.load_dataset("car_crashes")

In [ ]:
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA

In [ ]:
df.shape

(51, 8)

In [ ]:
df.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous',
       'ins_premium', 'ins_losses', 'abbrev'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=51, step=1)

In [ ]:
df.values

In [ ]:
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA

In [ ]:
df[["alcohol","not_distracted"]].head()

alcohol  not_distracted
0    5.640          18.048
1    4.525          16.290
2    5.208          15.624
3    5.824          21.056
4    3.360          10.920

In [ ]:
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA

In [ ]:
df.iloc[30:33]

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
30   11.2     1.792    3.136           9.632        8.736      1301.52   
31   18.4     3.496    4.968          12.328       18.032       869.85   
32   12.3     3.936    3.567          10.824        9.840      1234.31   

    ins_losses abbrev  
30      159.85     NJ  
31      120.75     NM  
32      150.01     NY

In [ ]:
df.iloc[0:3][["not_distracted","alcohol"]] #Tavsiye edilen format !!!!

not_distracted  alcohol
0          18.048    5.640
1          16.290    4.525
2          15.624    5.208

In [ ]:
df.iloc[2:12][["not_distracted","abbrev"]]

not_distracted abbrev
2           15.624     AZ
3           21.056     AR
4           10.920     CA
5           10.744     CO
6            9.396     CT
7           14.094     DE
8            5.900     DC
9           16.468     FL
10          14.820     GA
11          14.350     HI

In [ ]:
df.iloc[0,0]

18.8

In [ ]:
df.loc[0:3]

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR

In [ ]:
df.loc[0:3,"speeding"]

0    7.332
1    7.421
2    6.510
3    4.032
Name: speeding, dtype: float64

In [ ]:
df.loc[0:3,["speeding", "alcohol"]]

speeding  alcohol
0     7.332    5.640
1     7.421    4.525
2     6.510    5.208
3     4.032    5.824

In [ ]:
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA

In [ ]:
#absa<3

In [ ]:
#a[a<3]

In [ ]:
df["speeding"]>5

0      True
1      True
2      True
3     False
4     False
5      True
6     False
7      True
8     False
9     False
10    False
11     True
12     True
13    False
14    False
15    False
16    False
17    False
18     True
19     True
20    False
21    False
22    False
23    False
24    False
25     True
26     True
27    False
28     True
29    False
30    False
31    False
32    False
33     True
34     True
35    False
36     True
37    False
38     True
39    False
40     True
41     True
42    False
43     True
44    False
45    False
46    False
47    False
48     True
49    False
50     True
Name: speeding, dtype: bool

In [ ]:
df[df["speeding"]>5] #Tavsiye edilen format !!!!

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0    18.8     7.332    5.640          18.048       15.040       784.55   
1    18.1     7.421    4.525          16.290       17.014      1053.48   
2    18.6     6.510    5.208          15.624       17.856       899.47   
5    13.6     5.032    3.808          10.744       12.920       835.50   
7    16.2     6.156    4.860          14.094       16.038      1137.87   
11   17.5     9.450    7.175          14.350       15.225       861.18   
12   15.3     5.508    4.437          13.005       14.994       641.96   
18   20.5     7.175    6.765          14.965       20.090      1281.55   
19   15.1     5.738    4.530          13.137       12.684       661.88   
25   16.1     6.923    5.474          14.812       13.524       790.32   
26   21.4     8.346    9.416          17.976       18.190       816.21   
28   14.7     5.439    4.704          13.965       14.553      1029.87   
33   16.8     6.552    5.208          15.792       13.608       708.24   
34   23.9     5.497   10.038          23.661       20.554       688.75   
36   19.9     6.368    5.771          18.308       18.706       881.51   
38   18.2     9.100    5.642          17.472       16.016       905.99   
40   23.9     9.082    9.799          22.944       19.359       858.97   
41   19.4     6.014    6.402          19.012       16.684       669.31   
43   19.4     7.760    7.372          17.654       16.878      1004.75   
48   23.8     8.092    6.664          23.086       20.706       992.61   
50   17.4     7.308    5.568          14.094       15.660       791.14   

    ins_losses abbrev  
0       145.08     AL  
1       133.93     AK  
2       110.35     AZ  
5       139.91     CO  
7       151.48     DE  
11      120.92     HI  
12       82.75     ID  
18      194.78     LA  
19       96.57     ME  
25      144.45     MO  
26       85.15     MT  
28      138.71     NV  
33      127.82     NC  
34      109.72     ND  
36      178.86     OK  
38      153.86     PA  
40      116.29     SC  
41       96.87     SD  
43      156.83     TX  
48      152.56     WV  
50      122.04     WY

In [ ]:
df.T

0        1       2       3       4       5        6   \
total             18.8     18.1    18.6    22.4    12.0    13.6     10.8   
speeding         7.332    7.421    6.51   4.032     4.2   5.032    4.968   
alcohol           5.64    4.525   5.208   5.824    3.36   3.808    3.888   
not_distracted  18.048    16.29  15.624  21.056   10.92  10.744    9.396   
no_previous      15.04   17.014  17.856   21.28   10.68   12.92    8.856   
ins_premium     784.55  1053.48  899.47  827.34  878.41   835.5  1068.73   
ins_losses      145.08   133.93  110.35  142.39  165.63  139.91   167.02   
abbrev              AL       AK      AZ      AR      CA      CO       CT   

                     7        8        9   ...      41      42       43  \
total              16.2      5.9     17.9  ...    19.4    19.5     19.4   
speeding          6.156    2.006    3.759  ...   6.014   4.095     7.76   
alcohol            4.86    1.593    5.191  ...   6.402   5.655    7.372   
not_distracted   14.094      5.9   16.468  ...  19.012   15.99   17.654   
no_previous      16.038      5.9   16.826  ...  16.684  15.795   16.878   
ins_premium     1137.87  1273.89  1160.13  ...  669.31  767.91  1004.75   
ins_losses       151.48   136.05   144.18  ...   96.87  155.57   156.83   
abbrev               DE       DC       FL  ...      SD      TN       TX   

                    44      45      46      47      48      49      50  
total             11.3    13.6    12.7    10.6    23.8    13.8    17.4  
speeding         4.859    4.08   2.413   4.452   8.092   4.968   7.308  
alcohol          1.808    4.08   3.429   3.498   6.664   4.554   5.568  
not_distracted   9.944  13.056  11.049   8.692  23.086   5.382  14.094  
no_previous     10.848   12.92  11.176   9.116  20.706  11.592   15.66  
ins_premium     809.38   716.2  768.95  890.03  992.61  670.31  791.14  
ins_losses      109.48  109.61  153.72  111.62  152.56  106.62  122.04  
abbrev              UT      VT      VA      WA      WV      WI      WY  

[8 rows x 51 columns]

In [ ]:
df[(df["alcohol"] > 6) & (df["no_previous"] > 20)]

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
18   20.5     7.175    6.765          14.965       20.090      1281.55   
34   23.9     5.497   10.038          23.661       20.554       688.75   
48   23.8     8.092    6.664          23.086       20.706       992.61   

    ins_losses abbrev  
18      194.78     LA  
34      109.72     ND  
48      152.56     WV

## SECTION  : EXERCISES

### EXERCISE - 1

* Write a function that takes a list as an argument, assigns the odd and even numbers in the list to separate lists, and returns these lists.


In [ ]:
l = [1,2,3,4,10,18,93,22]
l

[1, 2, 3, 4, 10, 18, 93, 22]

In [ ]:
list1 = [1,2,3,'abc','klm']
list2 = [2,2,2,'dd']

In [ ]:
total_list = [list1,list2]
total_list3 =[]

In [ ]:
[total_list3.append(list1)].append(list2)

In [ ]:
total_list2.append(list2)

In [ ]:
total_list3

[[1, 2, 3, 'abc', 'klm']]

In [ ]:
total_list[0][3]

'abc'

In [ ]:
even_list = []
odd_list = []

for i in l:
    if i % 2 == 0:    #mod 
        print("Even:", i)
        even_list.append(i)
    else:
        print("Odd:", i)
        odd_list.append(i)

    print("Even Numbers:",even_list)
    print("Odd Number:",odd_list)

Odd: 1
Even Numbers: []
Odd Number: [1]
Even: 2
Even Numbers: [2]
Odd Number: [1]
Odd: 3
Even Numbers: [2]
Odd Number: [1, 3]
Even: 4
Even Numbers: [2, 4]
Odd Number: [1, 3]
Even: 10
Even Numbers: [2, 4, 10]
Odd Number: [1, 3]
Even: 18
Even Numbers: [2, 4, 10, 18]
Odd Number: [1, 3]
Odd: 93
Even Numbers: [2, 4, 10, 18]
Odd Number: [1, 3, 93]
Even: 22
Even Numbers: [2, 4, 10, 18, 22]
Odd Number: [1, 3, 93]


In [ ]:
odd_list

[2, 4, 10, 18, 22]

In [ ]:
even_list

[2, 4, 10, 18, 22]

In [ ]:
w = 2

In [ ]:
w

2

In [ ]:
w ==2

True

### EXERCISE - 2

* Read the car_crashes dataset in seaborn. Capitalize the names of the numeric variables. 
* Read the car_crashes dataset in seaborn. Capitalize the names of variables. 


* Read the car_crashes dataset in seaborn. Capitalize the names of the numeric variables. And add NUM into the beginning of them in the  dataset by using list comprehension.

In [19]:
import seaborn as sns

In [20]:
df = sns.load_dataset("car_crashes")
df.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA

In [21]:
df.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous',
       'ins_premium', 'ins_losses', 'abbrev'],
      dtype='object')

In [22]:
[u.upper() for u in df.columns]

['TOTAL',
 'SPEEDING',
 'ALCOHOL',
 'NOT_DISTRACTED',
 'NO_PREVIOUS',
 'INS_PREMIUM',
 'INS_LOSSES',
 'ABBREV']

In [23]:
new_columns = [u.lower() for u in df.columns]

In [24]:
new_columns

['total',
 'speeding',
 'alcohol',
 'not_distracted',
 'no_previous',
 'ins_premium',
 'ins_losses',
 'abbrev']

In [25]:
new_columns = [u.upper() for u in df.columns]

In [26]:
df.columns = new_columns

In [27]:
df.head()

TOTAL  SPEEDING  ALCOHOL  NOT_DISTRACTED  NO_PREVIOUS  INS_PREMIUM  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   INS_LOSSES ABBREV  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA

## SECTION : PYTHON COMPREHENSION

In [28]:
abc=[]
for col in df.columns:
  abc.append(col.upper())
  #print(col.upper())
abc

['TOTAL',
 'SPEEDING',
 'ALCOHOL',
 'NOT_DISTRACTED',
 'NO_PREVIOUS',
 'INS_PREMIUM',
 'INS_LOSSES',
 'ABBREV']

In [29]:
df.columns

Index(['TOTAL', 'SPEEDING', 'ALCOHOL', 'NOT_DISTRACTED', 'NO_PREVIOUS',
       'INS_PREMIUM', 'INS_LOSSES', 'ABBREV'],
      dtype='object')

In [30]:
[col.upper() for col in df.columns]

['TOTAL',
 'SPEEDING',
 'ALCOHOL',
 'NOT_DISTRACTED',
 'NO_PREVIOUS',
 'INS_PREMIUM',
 'INS_LOSSES',
 'ABBREV']

In [31]:
["NUM_"+ col.upper() if df[col].dtype != "O" else col.upper()  for col in df.columns]

['NUM_TOTAL',
 'NUM_SPEEDING',
 'NUM_ALCOHOL',
 'NUM_NOT_DISTRACTED',
 'NUM_NO_PREVIOUS',
 'NUM_INS_PREMIUM',
 'NUM_INS_LOSSES',
 'ABBREV']